### PR TITLE
Add some usability tweaks for initial setup to main.py and tags.py

### PR DESCRIPTION
**Pull request by actioninja**
Those ui tweaks that you wanted merged into the main cacobot are finally here.  If this pull gets closed again I'm gonna stab a bitch.

### CODE REVIEW

**Comment by SteelSliver** [comment]
watta goy

**Comment by Orangestar12** [comment]
Iirc, trying to `dump` a blank dictionary actually outputs a blank file, which raises an error when you try to `parse` it, so you have to `write` to the filesystem a pair of braces.

**Comment by actioninja** [comment]
Some changes were made to fix the blank dump problem and also fix that because the config load in tags also errors because it's imported.  There are other examples, I need to go through and make sure anywhere the config loads is caught.

**Comment by actioninja** [comment]
It should be clear now.  You can check out the changes for youself, but everything should actually work now.

**Comment by actioninja** [comment]
I lied, it still doesn't work and now I can't figure out why

**Comment by SteelSliver** [comment]
wow

**Comment by Orangestar12** [comment]
i think this has been left stagnant long enough to be considered ded

**Pull request closed without merging**
